name: Docker Oathkeeper
on:
  push:
    branches:
      - master
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.3'
      - run: go build .
      - uses: botpress/gh-actions/build/docker@v2
        with:
          repository: oathkeeper
